default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
development:
  <<: *default
  database: achieve_development
test:
  <<: *default
  database: achieve_test
production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>